### ISSUE TITLE
Unable to instantiate error with non literal string

### ISSUE THREAD

**Issue by eduardomourar** [Stedi/ts2asl#112]
On version `0.1.28` of `@ts2asl/asl-lib`, I was able to do (playground [here](https://asl-editor-spike-ts-stedi.vercel.app/?aW1wb3J0ICogYXMgYXNsIGZyb20gIkB0czJhc2wvYXNsLWxpYiIKCi8vbWFpbiB3aWxsIGJlIGNvbnZlcnRlZCB0byBBU0wgYW5kIGRlcGxveWVkIGFzIGEgc3RhdGUgbWFjaGluZQpleHBvcnQgY29uc3QgbWFpbiA9IGFzbC5kZXBsb3kuYXNTdGF0ZU1hY2hpbmUoYXN5bmMgKGlucHV0OiBJSW5wdXQpID0+IHsKICBpZiAodHlwZW9mIGlucHV0Lm5hbWUgIT09ICJzdHJpbmciKSB7CiAgICBpbnB1dC5uYW1lID0gIldvcmxkIjsKICB9CiAgY29uc3Qgcm5kID0gYXdhaXQgcmFuZG9tKCk7CiAgcmV0dXJuIHsKICAgIGdyZWV0aW5nOiBgSGVsbG8gJHtpbnB1dC5uYW1lfWAsCiAgICBsdWNreU51bWJlcjogcm5kCiAgfQp9KTsKCi8vcmFuZG9tIHdpbGwgYmUgZGVwbG95ZWQgYXMgYSBsYW1iZGEgZnVuY3Rpb24KZXhwb3J0IGNvbnN0IHJhbmRvbSA9IGFzbC5kZXBsb3kuYXNMYW1iZGEoYXN5bmMgKGlucHV0OiB7IG1pbj86IG51bWJlcjsgbWF4PzogbnVtYmVyIH0gPSB7fSkgPT4gewogIGNvbnN0IG1pbiA9IGlucHV0Lm1pbiA/PyAwOwogIGNvbnN0IG1heCA9IGlucHV0Lm1heCA/PyAxMDA7CiAgcmV0dXJuIE1hdGgucm91bmQoTWF0aC5yYW5kb20oKSAqIChtYXggLSBtaW4pICsgbWluKTsKfSk7CgppbnRlcmZhY2UgSUlucHV0IHsKICBuYW1lOiBzdHJpbmc7Cn0K)):

```typescript
import * as asl from "@ts2asl/asl-lib"

export const main = asl.deploy.asStateMachine((_: any) => {
  const error = {
    message: "Some Error Message"
  };
  throw new Error(error.message);
});
```

Now, I get the following error:
> Error: error thrown must have string literal as argument

**Comment by OlafConijn** [comment]
a previous version of `@ts2asl/converter` might have accepted this, but it would not have resulted in valid ASL as the following is not supported by AWS:
```   
   "Assign error": {
      "Type": "Pass",
      "Result": {
        "message": "Some Error Message"
      },
      "ResultPath": "$.vars.error",
      "Next": "Throw Error"
    },
    "Throw Error": {
      "Type": "Fail",
      "Error": "Error",
      "Cause.$": "$.vars.error.message", //not supprted
      "Comment": "source: throw new Error(\"Some Error Message\");"
    }
```

if the intention is declare a variable once and use it multiple times you can so it using `asl.deploy.evalConst`:
``` typescript
const error = "Some Error Message";
export const main = asl.deploy.asStateMachine((_: any) => {
  throw new Error(asl.deploy.evalConst(error));
});
```

**Comment by eduardomourar** [comment]
The intent was to create an error from a lambda function's response, for instance. I dig the actual commit where that was working again.

**Comment by OlafConijn** [comment]
makes sense. i dont believe this is possible in ASL. unless you throw the error with the right message/cause from within the lambda (using `asl.runtime.createError`).

if you find a way to do this in ASL, let me know

**Comment by OlafConijn** [comment]
@eduardomourar , can this be closed?
