### ISSUE TITLE
CLI or local call example

### ISSUE THREAD

**Issue by amttr** [Stedi/ts2asl#118]
At closed pull requests I've found that some kind of a CLI was mentioned.
Could you provide a reference or an example of how to translate TS to ASL locally, the same way as it is done at the playground?

**Comment by OlafConijn** [comment]
Thanks for creating this issue. As we, internally, use the CDK to deploy AWS infrastructure there is currently no standalone CLI to do this. I agree it makes sense to have a standalone CLI. Will update this issue once we have one 🙂

**Comment by OlafConijn** [comment]
better late than never! 

``` bash
echo "import * as asl from "@ts2asl/asl-lib"

export const main = asl.deploy.asStateMachine(async (input: unknown) => {
  console.log(input);
  return "ok"
});" > test.ts

npx ts2asl compile test.ts
```
