### ISSUE TITLE
CDK v2 support?

### ISSUE THREAD

**Issue by abury** [Stedi/ts2asl#73]
Howdy all.

Looks like an amazing project! Was super excited to try it out, but it looks like you only support CDK v1, which is becoming end of life pretty soon :(

Is V2 support in the works couldn't see anything about it in issues or the readme.

**Comment by OlafConijn** [comment]
thanks for raising the issue, we are working on this.

**Comment by abury** [comment]
Oh wow, what a quick turn around @OlafConijn!
