### ISSUE TITLE
Broken in current form

### ISSUE THREAD

**Issue by dmeehan1968** [Stedi/ts2asl#888]
I've installed latest from npm, and following the examples it no longer appears to work.  ts2asl produces:

```
 ›   Error: no step function found, try the following source:
 ›
 ›
 ›   import * as asl from "@ts2asl/asl-lib"
 ›
 ›   export const main = asl.deploy.asStateMachine(async (input: unknown) => {
 ›     console.log(input);
 ›     return "ok"
 ›   });

```

It does this when the input is the stated example.

Trying to use the CDK construct the 'functions' and 'stateMachines' properties of the returned instance are empty, and stepping into the code seems to suggest that the sources are loaded ok but that the routines to extract the exports return nothing.

I've checked my own tsconfig.json to see if it aligns with the examples and it does, except that I target ES2022, but it still fails if I use the ES2018 from the examples.

**Comment by dmeehan1968** [comment]
I took another run at it and figured out that its just inaccurate documentation that caused it not to work as described.  I'm going to create separate issues as there are a number of things that are important.

**Comment by ZackKanter** [comment]
> I took another run at it and figured out that its just inaccurate documentation that caused it not to work as described. I'm going to create separate issues as there are a number of things that are important.

Thanks! Would you be willing to contribute a PR for correcting the inaccurate documentation?

**Comment by dmeehan1968** [comment]
> > I took another run at it and figured out that its just inaccurate documentation that caused it not to work as described. I'm going to create separate issues as there are a number of things that are important.
> 
> Thanks! Would you be willing to contribute a PR for correcting the inaccurate documentation?

I've added a bunch of issues for things I'm finding as I experiment.  I may well do some PR's but I'm just trying to work out if its going to save me time over ASL/CDK construction.  I like the concept, but I'm new to step functions and trying to work out a good workflow for myself in using them.
